/*
  Snippet generated by johnnesta2018@gmail.com
*/
require("dotenv").config()

const mongoose = require("mongoose")
const cors = require("cors");
const express = require("express");
const path = require("path");

const { 
  TeacherRoute, SchoolRoute, ClassRoute, 
  StudentRoute, SubjectRoute, AnalyticsRoute, 
  MarketRoute 
} = require("./routes");

const PORT = process.env.PORT || 3500
const app = express()

app.use(express.json())
app.use(express.urlencoded({extended:true}))
// app.use(cors())

// simple routes
app.use(express.static(path.join(__dirname, 'public/build')));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public/build', 'index.html'));
});

app.use("/school", SchoolRoute);
app.use("/teacher", TeacherRoute);
app.use("/grade", ClassRoute);
app.use("/learner", StudentRoute);
app.use("/subject", SubjectRoute);
app.use("/analytics", AnalyticsRoute);
app.use("/market", MarketRoute); // for purchasing stuff in the school solution :)

// start mongodb
mongoose.connect(process.env.MONGO_URI)
  .then(_ => {
      app.listen(PORT, () => {
        console.log("server started listening on port: "+PORT)
      })
  })
  .catch(console.error)