/*
  This snippet has been generated by johnnesta2018@gmail.com
*/

const mongoose = require("mongoose")

// we can create this as many as we want
const classSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },

    // used to suspend classes after the year or something
    isClosed: {
        type: Boolean,
        default: false
    },

    // a link back to the school just incase
    schoolID: {
        type: String,
        required: true
    },

    // a stream if available
    stream: {
        type: String,
    },

    // for grouping classes per year ( but we dont have to design it this way )
    year: {
        type: Number,
        required: true
    },

    // all the subjects taught within a given class
    subjects: [
        {
            type: mongoose.Types.ObjectId,
            ref: "class_subjects"
        }
    ],

    // this is the teacher responsible for the class
    classTeacher: {
        type: mongoose.Types.ObjectId,
        ref: "teacher"
    },

    // we just need a ref to an actual zoezi account :)
    classRef: {
        type: mongoose.Types.ObjectId,
        ref: "User" // the normal zoezi user
    }
})

module.exports = mongoose.model("class_unit",classSchema)