/*
  This snippet has been generated by johnnesta2018@gmail.com
*/

const mongoose = require("mongoose")

// this are t
const midTier = new mongoose.Schema({
    // this refers to the actual name or the years for the yeared papers
    // unique per each paper set
    name: {
        type: String,
        required: true,
        // unique: true --> we will enforce this ourselves
    },

    available: {
        type: Boolean,
        default: false 
    },

    color: {
        type: String,
        default: "#4db6ac"
    },

    secondTier: {
        type: mongoose.Types.ObjectId,
        ref: 'secondTier'
    },
    // get all the years then display them on a floating spinner
    papers: [{
        type: mongoose.Types.ObjectId,
        ref: 'special_paper'
    }]
})

module.exports = mongoose.model("midTier", midTier)