/*
  This snippet has been generated by johnnesta2018@gmail.com
*/

const mongoose = require("mongoose")

// we can create subjects with different time periods
// how do we do this
// we will have it this way 
// index with years (unique)
// foreach paper we have the year and the pointer to the subjects 
// that support it

const multiLevelPapers = new mongoose.Schema({
    name: {
        type: String,
        required: true,
        unique: true
    },

    available: {
        type: Boolean,
        default: false 
    },

    // not really required hapa
    // but it should

    // displayImage: {
    //     type: String,
    // },

    // this will be the last papers so no worries there
    // but if and when needed we will add support of arranging

    // a reference to a grade like thing here
    // we have normal papers
    // we also have the revision papers instance
    // we want to save the network roundtrip in fetching ?

    children: [{
        type: mongoose.Types.ObjectId,
        ref: 'secondTier'
    }],

    createdAt: {
        type: Date,
        default: Date.now
    }
})

module.exports = mongoose.model("multiLevelPaper", multiLevelPapers)