/*
  This snippet has been generated by johnnesta2018@gmail.com
*/

const mongoose = require("mongoose")

const onlineSchools = new mongoose.Schema({
    // this is the link to the school that we need for other things :)
    schoolID: {
        type: String,
        required: true,
        unique: true
    }, 

    isOnline: {
        type: Boolean,
        default: false
    },

    socketioID: {
        type: String,
        required: true,
        unique: true
    }
})

module.exports = mongoose.model("currently_online_schools",onlineSchools)