/*
  This snippet has been generated by johnnesta2018@gmail.com
*/

const mongoose = require("mongoose")

// have root images for this in the system
// later create a way to directly upload them
// top level/name.png or whatever
const secondTierSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true,
        unique: true
    },

    available: {
        type: Boolean,
        default: false
    },

    color: {
        type: String,
        default: "#4db6ac"
    },

    // this is a boolean used to verify the names or years u enter into the lower level stuff
    isYeared: {
        type: Boolean,
        default: false
    },

    // a reference from whence it came from
    topLevelPaper: {
        type: mongoose.Types.ObjectId,
        ref: "multiLevelPaper"
    },

    midTiers: [{
        type: mongoose.Types.ObjectId,
        ref: 'midTier'
    }],

    // used for UI arrangement
    // create a rearranging thing that does this
    priority: {
        type: Number,
        default: 0
    },
})

module.exports = mongoose.model("secondTier", secondTierSchema)