/*
  This snippet has been generated by johnnesta2018@gmail.com
*/

const mongoose = require("mongoose");

const teacherSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },

    //  link back to the school
    schoolID: {
        type: mongoose.Types.ObjectId,
        ref: "school"
    },

    // used for login
    email: {
        type: String,
        required: true,
        unique: true
    },

    // the password
    password: {
        type: String,
        required: true
    },

    // encrypted 
    encryptedPassword: {
       type: String, 
    },

    // link to the subjects they are teaching
    subjects: [
        {
            type: mongoose.Types.ObjectId,
            ref: "class_subjects"
        }
    ],

    // grades that they are class teachers in
    grades: [
        {
            type: mongoose.Types.ObjectId,
            ref: "class_unit"
        }
    ]
})

module.exports = mongoose.model("teacher",teacherSchema)